# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cdcf85416c4512296d2f3437c4ce6460c9ef30c463698297c84f66112d6f191af390251b1580ae10592b4fbf5349d9b765bf4ac59093d8adb978c12b9eecfa9

test:
  secret_key_base: a1c052f1abc7145414d5abf1794f991a90288df065e28ffe952275d995ad945e12bb189b8156dfd857852de4da9affa01465bfbfaf2e33938599f04d9c6627f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
